language: java
jdk:
  - oraclejdk8
dist: trusty

addons:
  sonarcloud:
    organization: "glescroel"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar -Dsonar.projectKey=GLescroel_eBibli -Dsonar.login=ae2e527979c2c9445d5c80faa13b734aaa8e39f8
