version: '2'
services:
  myerp.db:
    image: postgres:9.4
    restart: always
    ports:
      - "127.0.0.1:9032:5432"
    environment:
      - POSTGRES_DB=eBibli
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apollineL16*
    volumes:
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
       - "./postgres-data:/var/lib/postgresql/data"
volumes:
  postgres-data:      
